version: "3.8"

services:
  # MongoDB
  mongodb:
    image: mongo:7
    container_name: ecommerce-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ecommerceDB
    networks:
      - ecommerce-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: ecommerce-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ecommerce-network

  # Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ecommerce-server
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/ecommerceDB
      - JWT_SECRET=supersecretkey
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - CLIENT_URL=http://localhost:5173
      - CLOUDINARY_NAME=${CLOUDINARY_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - HOST_IP=${HOST_IP}
    depends_on:
      - mongodb
      - redis
    networks:
      - ecommerce-network

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ecommerce-client
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - server
    networks:
      - ecommerce-network

volumes:
  mongodb_data:
  redis_data:

networks:
  ecommerce-network:
    driver: bridge
