import RecommendationAnalytics from "../models/recommendationAnalyticsModel.js";
import Product from "../models/Product.js";

// Fetch recommendation performance analytics for Admin Dashboard
export const getAnalytics = async (req, res) => {
  try {
    const totalImpressions = await RecommendationAnalytics.countDocuments({
      action: "recommended",
    });

    const totalClicks = await RecommendationAnalytics.countDocuments({
      action: "clicked",
    });

    const totalConversions = await RecommendationAnalytics.countDocuments({
      action: "purchased",
    });

    const clickThroughRate = totalImpressions > 0 
      ? ((totalClicks / totalImpressions) * 100).toFixed(2)
      : "0.00";

    const conversionRate = totalClicks > 0
      ? ((totalConversions / totalClicks) * 100).toFixed(2)
      : "0.00";

    // Calculate revenue generated by recommendations (purchased action products)
    const purchases = await RecommendationAnalytics.find({ action: "purchased" })
      .populate("product", "price");

    const revenue = purchases.reduce((acc, item) => {
      if (item.product) {
        const priceStr = typeof item.product.price === "string" 
          ? item.product.price 
          : "RS 0";
        const numericPrice = parseFloat(priceStr.replace("RS ", "").trim()) || 0;
        return acc + numericPrice;
      }
      return acc;
    }, 0);

    // Aggregate click counts by product to find popular items
    const popularAggregation = await RecommendationAnalytics.aggregate([
      { $match: { action: "clicked" } },
      { $group: { _id: "$product", count: { $sum: 1 } } },
      { $sort: { count: -1 } },
      { $limit: 5 }
    ]);

    const popularProducts = await Product.populate(popularAggregation, {
      path: "_id",
      select: "name price image"
    });

    res.json({
      success: true,
      totalImpressions,
      totalClicks,
      totalConversions,
      clickThroughRate: `${clickThroughRate}%`,
      conversionRate: `${conversionRate}%`,
      revenueGenerated: `RS ${revenue.toFixed(2)}`,
      popularProducts: popularProducts.map((p) => ({
        product: p._id,
        count: p.count
      }))
    });
  } catch (error) {
    console.error("Get Analytics Error:", error);
    res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};
